bank_website/bankproject/bankproject/bankproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('credentialsapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bank_website/bankproject/bankproject/credentialsapp/urls.py
from.import views
from django.urls import path


urlpatterns=[
    path('',views.home,name='home'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('page',views.page,name='page'),
    path('account_create_view',views.account_create_view,name='account_create_view'),
    path('get_branches/<int:district_id>/', views.get_branches,name='get_branches'),



]

bank_website/bankproject/bankproject/credentialsapp/models.py
from django.db import models

class District(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
class Branch(models.Model):
    name = models.CharField(max_length=200)
    district = models.ForeignKey(District, on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Account(models.Model):
    GENDER_CHOICES = [('M', 'Male'), ('F', 'Female')]
    ACCOUNT_TYPE_CHOICES = [('S', 'Savings'), ('C', 'Current')]


    name = models.CharField(max_length=200,blank=True)
    dob = models.DateField(blank=True)
    age = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES,blank=True)
    phone_number = models.CharField(max_length=10,blank=True)
    email = models.EmailField(blank=True)
    address = models.TextField(blank=True)
    district = models.ForeignKey(to=District, on_delete=models.CASCADE,blank=True)
    branch = models.ForeignKey(to=Branch, on_delete=models.CASCADE,blank=True)
    account_type = models.CharField(max_length=1, choices=ACCOUNT_TYPE_CHOICES,blank=True)

bank_website/bankproject/bankproject/credentialsapp/forms.py
from django import forms
from .models import District, Branch, Account


class AccountForm(forms.ModelForm):
    DEBIT_CARD = 'DC'
    CREDIT_CARD = 'CC'
    CHEQUE_BOOK = 'CB'

    MATERIAL_CHOICES = [
        (DEBIT_CARD, 'Debit Card'),
        (CREDIT_CARD, 'Credit Card'),
        (CHEQUE_BOOK, 'Cheque Book'),
    ]

    materials = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=MATERIAL_CHOICES,
    )
    class Meta:
        model = Account
        fields = '__all__'

bank_website/bankproject/bankproject/credentialsapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse,JsonResponse
from .forms import AccountForm

from .models import District,Branch

from django.shortcuts import render, redirect, get_object_or_404

app_name='credentialsapp'
# Create your views here.

def home(request):
    return render(request,"base.html")
def page(request):
    return render(request,"page.html")

def account_create_view(request):
    form = AccountForm(request.POST or None)
    if form.is_valid():
        form.cleaned_data['materials']
        form.save()
        return render(request,"base.html",{'form':form})

    return render(request, "registerationform.html", {'form':form})
def get_branches(request, district_id):
    branches = Branch.objects.filter(district_id=district_id).values('id','name')
    branch_list=list(branches)
    return JsonResponse(list(branches), safe=False)






def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"Invalid credentials")
            return HttpResponse("Invalid credentials")
    return render(request,"login.html")
def register(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"Username Already exists")
                return redirect('register')


            else:

                user=User.objects.create_user(username=username,password=password)
                user.save();

                return redirect('login')


        else:
            messages.info(request,"Password not matching")
            return redirect('register')
        return redirect('/')
    return render(request,"register.html")
def logout(request):
    auth.logout(request)
    return redirect('/')

bank_website/bankproject/bankproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <script src="https://kit.fontawesome.com/7972f76a8a.js" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">


    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
    {% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

bank_website/bankproject/bankproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <p class="text-center">&copy; GT Bank Pvt Ltd.All rights reserved</p>
</div>

bank_website/bankproject/bankproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>

<style>
body {
  background-image: url('https://callcia.com/wp-content/uploads/2019/08/Form-background-image-2.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}
</style>
<h1 style ="text-align:center;font-size:160%;color:black;">Login</h1>
<form style="text-align:center;" action="login" method="post">
    {% csrf_token %}
    <input type="text" class="shadow-form-control" name="username" placeholder="Enter username"><br>
    <input type="password" name="password" placeholder="Enter Password"><br>
    <button type="submit" formaction="{% url 'page' %}">Submit</button><br>
    <button type="submit" name="registerlink"><a href="{% url 'register' %}">Register link</a></button>
</form>

</html>

bank_website/bankproject/bankproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li>
        <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
  Branches
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Ernakulam">Ernakulam</a></li>
    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a></li>
    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Idukki_district">Idukki</a></li>
    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a></li>
    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Trivandrum</a></li>
    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kollam">Kollam</a></li>
    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a></li>
    <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thrissur">Thrissur</a></li>
  </ul>
        </div>
      </ul>
    </div>

</nav>
<div>
    <img class="my_image my_image_padding" src="https://i.pinimg.com/originals/1c/e6/3d/1ce63dcbcc968187b0e9b0261aeada5e.jpg" alt="" width="1110px;"height="600px;" >
</div>
</div>
<div style="text-align:center">
  <a class="btn btn-success"  href="{% url 'login' %}">Login Here</a>
</div>

bank_website/bankproject/bankproject/templates/page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application</title>
</head>

<style>
body {
  background-image: url('https://th.bing.com/th/id/OIP.JwPbNjiqQ_gtCZu70IVrKAHaFj?pid=ImgDet&rs=1');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}
</style>
<h1 style ="text-align:center;font-size:160%;color:black">Click below for the Application form</h1>
<form style="text-align:center;color:black;" action="login" method="post">
    {% csrf_token %}

    <button type="submit" formaction="{% url 'account_create_view' %}">Apply Online</button>
</form>
</body>
</html>

bank_website/bankproject/bankproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<style>
body {
  background-image: url('https://th.bing.com/th/id/OIP.FRec2HtcENV8w_fJ3n0LiQHaFC?w=274&h=186&c=7&r=0&o=5&dpr=1.3&pid=1.7');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: 100% 100%;
}
</style>
<h1 style ="text-align:center;font-size:160%;color:black">Registration</h1>

<form style="text-align:center;" action="register" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter username"><br>
    <input type="password" name="password" placeholder="Enter Password"><br>
    <input type="password" name="password1" placeholder="Enter confirm password"><br>
    <input type="submit">
</form>
{% for msg in messages %}
{{msg}}
{% endfor %}

</body>
</html>

bank_website/bankproject/bankproject/templates/registerationform.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Application Form</title>
</head>
<body style="text-align:center;background-image:url('https://primelegalstaff.com/wp-content/uploads/2016/11/application-background1.jpg');">
<h1 style="text-align:center;color:black;font-family:veranda;font-size:160%;">Application Form</h1>
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}

</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
  $('#id_district').change(function() {
    var url = "/get_branches/" + $(this).val() + "/";
    $.ajax({
        url: url,
        success: function(data) {
            var options = '<option value="">---------</option>';
            for (var i=0; i<data.length; i++) {
                options += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
            }
            $('#id_branch').html(options);
        }
    });
});

});
</script>

</body>


<!--<div class="container">-->

<!--<form style="margin:15px;padding:0;line-height:40px;text-align:center;" >-->
<!--    {% csrf_token %}-->

<!--    <label>Name</label>-->
<!--    <input type="text" name="name"><br>-->
<!--    <label>Date of Birth</label>-->
<!--    <input type="date" name="dob"><br>-->
<!--    <label>Age</label>-->
<!--    <input type="number" name="age"><br>-->
<!--    <label>Gender</label>-->
<!--    <select id="gender" name="gender">-->
<!--        <option value=""></option>-->
<!--        <option value="male">Male</option>-->
<!--        <option value="female">Female</option>-->
<!--        <option value="other">Other</option>-->
<!--    </select><br>-->
<!--    <label>Phone Number</label>-->
<!--    <input type="tel" name="phone"><br>-->
<!--    <label>Mail Id</label>-->
<!--    <input type="email" name="email"><br>-->
<!--    <label >Address</label>-->
<!--    <textarea id="address" name="address"></textarea><br>-->

<!-- <label>District</label>-->
<!--    <select name="district">-->

<!--            <option value="{{district.id}}" >{{district.name}}</option>-->
<!--    </select>-->

<!--<label>Branch</label>-->
<!--    <select name="branch">-->
<!--        {% for i in branches %}-->
<!--            <option value="{{ i.id }}">{{ i.name }}</option>-->
<!--        {% endfor %}-->
<!--    </select><br>-->


<!--<label>Account type</label>-->
<!--    <select name="account_type">-->
<!--        <option  value="select account type"></option>-->
<!--        <option  value="savings">Savings Account</option>-->
<!--        <option  value="current">Current Account</option>-->
<!--    </select><br>-->
<!--    <label>Materials Provided:</label>-->
<!--    <input type="checkbox" name="materials[]" value="debit_card">Debit Card-->
<!--    <input type="checkbox" name="materials[]" value="credit_card">Credit Card-->
<!--    <input type="checkbox" name="materials[]" value="cheque_book">Cheque Book<br>-->


    <form id="myForm">
    <input type="submit" value="Submit" onclick="return confirmBox()" value="Submit">
        <input type="submit" value="logout" onclick="{% url 'logout' %}">
</form>

<script>
function confirmBox() {
    var txt;
    if (confirm("Click OK to go to Home page, or Cancel to stay on this page.")) {
        window.location.href = "{% url 'home' %}";
    }
    return false;
}
</script>


</form>

<!--</div>-->

<!--</body>-->
<!--</html>-->

bank_website/bankproject/bankproject/templates/success.html
<!DOCTYPE html>
<html>
<head>
    <title>Application Submitted</title>
</head>
<body>
    <h1>Application Accepted</h1>
    <p>Your application has been successfully submitted.</p>
    <a href="/">Return to Home Page</a>
</body>
</html>